### PR TITLE
#333 Internationalization and Localization Support

### PR DESCRIPTION
**Pull request by kennethbruskiewicz**
- Created a "Template" class for schema and documentation management which responds to locale changes
- Added support for i18n to be managed through a translation.json file informed by @ddooley 
- Added a "Language" UI component

Next steps:
- Refactor existing schema injection to use the Template object
- Test the coupling between the UI component and schema changes
- Contact researchers requiring localization and get instructed on their use-cases for controls
- Come up with example data for implementing the internationalization behaviour
- Show LinkML community the work and address pain-points
  - schemas don't know their language so it's a property of the way templates are packaged

### CODE REVIEW

**Comment by pkalita-lbl** [comment]
Yes I can take a look at this today or tomorrow!

**Comment by kennethbruskiewicz** [comment]
Some bugs came out in testing.

Also one extra request c/o @ddooley , support `translations.json` option for additional mapping in "`<template>/locales/translations.json`".

**Comment by kennethbruskiewicz** [comment]
Update on the completion status of this PR:
- The DataHarmonizer should still "work offline", i.e. as a standalone HTML file rather than provided through a server. (this was broken when I used `fetch` to access schema information)
- Cut/paste should now transfer i18n information between cells within the column. Between columns won't paste i18n compatibility. There is a kink where cutting and pasting into the same column won't work, which I'll fix as a separate issue.
- Exports should be in the default language, rather than the most recently translated language.
- Enum menus should be translated all the way through in whatever localization language is active.

There were many features that were affected by i18n, but the features themselves should be stable or only require hot fixes in the near future. Existing workflows should not be affected.

For codebase cleanup PRs, I'll make better use of the Template class I'm setting up plus optimize for better performance and bundle size, as well as enforcing the use of top-directory relative paths for module references. Also consolidate `menu.json` with `manifest.json` so schemas and their discoverability by the application can be further decoupled.

**Comment by Takadonet** [comment]
Thanks for working on this PR. We host a version of the Data Harmonizer and having localization support will make our lives easier to address concern from our external partners.

**Comment by ddooley** [comment]
The DH pull is just about ready for testing.  I'll let you know later today but you can actually see it in action with the TEST template in pull request's #410 branch 333-localization-i18n. It contains 2 separate test (french or whatever language you want) translation files:
- one for all the interface messaging, held in DH /web/translations/ - this isn't yet a complete interface text replacement, and its translations are a GOOGLE translate hack so all need to be reviewed / revised.  
- and then another for each particular template's terms.  For the TEST template you will see web/templates/test/locales/fr-FR/schema.json - this is the version of main schema with translated strings - AGAIN DONE BY GOOGLE TRANSLATE SO LIKELY WIERD IN PLACES.  ITS actually only slots like "title", "name", "description" and "slot_group" that are needed, the rest of the parameters in the schema don't need to be there insofar as original schema should control those.

**Comment by kennethbruskiewicz** [comment]
> Thanks for working on this PR. We host a version of the Data Harmonizer and having localization support will make our lives easier to address concern from our external partners.

@Takadonet Would you be interested in giving this branch a test run this week? There are a lot of changes, and I would like a user to attempt to use the application to ensure the new features offer a smooth experience.

**Comment by kennethbruskiewicz** [comment]
@ddooley I needed to rework the multi select internationalization to have a simpler implementation, particularly so copy-paste was less fragile.

**Comment by kennethbruskiewicz** [comment]
@ddooley I believe you've tested all of the changes made two weeks ago for i18n support (multi select menus are translated, provide values, and switch back and forth between languages; exports are in the default language; cut/paste should work robustly; DH works when opening the main HTML file as well as on a server).

I've also patched the problem with Chrome requiring clicking the localization button twice to get it to change(handle selecting a locale with onChange rather than onClick).

**Comment by Takadonet** [comment]
Bump.
Any chance that this will be merged in the near future? Theses changes will be awesome to have.

**Pull request closed without merging**
